### ISSUE TITLE
ikfastpy_ Compilation of free0

### ISSUE THREAD

**Issue by CodingNovice7** [IrisLi17/bridge_construction#1]
Thank you for your open source. This is a very good project, but I encountered some problems when calling the simulation environment written in pybullet in another Python version. I hope I can get your help. In fact, I think it's mainly ikfastpy_ For the compilation of free0, in ikfastpy, you can use setup Py gives ikfastpy_ Free4 compilation process, but I compile ikfastpy in the same way_ After free0 is imported, an error is reported: "importerror: dynamic module does not define model export function (pyinit_ikfastpy_free0)"！

**Comment by IrisLi17** [comment]
Hi, the `*.so` files inside `env/ikfastpy` are compiled with ubuntu 16 + python 3.6. To re-compile, you need to modify "free4" to "free0" in these two lines https://github.com/IrisLi17/bridge_construction/blob/34d75e7fbac438d0607b286e03beffdf05d3102f/env/ikfastpy/ikfast_wrapper.cpp#L65, https://github.com/IrisLi17/bridge_construction/blob/34d75e7fbac438d0607b286e03beffdf05d3102f/env/ikfastpy/setup.py#L5, then delete the files generated from your last compilation process, and try `python setup.py build_ext --inplace`. Note that only python3 works, you may need to check the python version you use for compiling.

**Comment by lylwy** [comment]
> 嗨，里面的文件是用ubuntu 16 + python 3.6编译的。要重新编译，您需要在这两行中将"free4"修改为"free0"`*.so``env/ikfastpy`
> 
> https://github.com/IrisLi17/bridge_construction/blob/34d75e7fbac438d0607b286e03beffdf05d3102f/env/ikfastpy/ikfast_wrapper.cpp#L65
> 
> ,
> https://github.com/IrisLi17/bridge_construction/blob/34d75e7fbac438d0607b286e03beffdf05d3102f/env/ikfastpy/setup.py#L5
> 
> ，然后删除上次编译过程中生成的文件，并尝试 。请注意，只有python3可以工作，您可能需要检查用于编译的python版本。`python setup.py build_ext --inplace`
中国人不骗中国人。

**Comment by CodingNovice7** [comment]
> 嗨，里面的文件是用ubuntu 16 + python 3.6编译的。要重新编译，您需要在这两行中将"free4"修改为"free0"`*.so``env/ikfastpy`
> 
> https://github.com/IrisLi17/bridge_construction/blob/34d75e7fbac438d0607b286e03beffdf05d3102f/env/ikfastpy/ikfast_wrapper.cpp#L65
> 
> ,
> https://github.com/IrisLi17/bridge_construction/blob/34d75e7fbac438d0607b286e03beffdf05d3102f/env/ikfastpy/setup.py#L5
> 
> ，然后删除上次编译过程中生成的文件，并尝试 。请注意，只有python3可以工作，您可能需要检查用于编译的python版本。`python setup.py build_ext --inplace`

中国人不骗中国人

**Comment by IrisLi17** [comment]
请问您的问题解决了吗？如果仍有问题，您可以贴出报错，我会尽力帮您解决；没有问题的话我会关闭这个issue

**Comment by CodingNovice7** [comment]
> 请问您的问题解决了吗？如果仍有问题，您可以贴出报错，我会尽力帮您解决；没有问题的话我会关闭这个issue

还没，我在按照你说的编译了ikfastpy_free0后，在导入他的时候会出现错误：“dynamic module does not define module export function(PyInit_ikfastpy_free0)”

**Comment by CodingNovice7** [comment]
> 请问您的问题解决了吗？如果仍有问题，您可以贴出报错，我会尽力帮您解决；没有问题的话我会关闭这个issue

这个问题已经解决了，谢谢您！
