### ISSUE TITLE
Strategy output after bridge construction

### ISSUE THREAD

**Issue by CodingNovice7** [IrisLi17/bridge_construction#2]
Hello, I recently noticed when looking at this code that when the bridge is built, the strategy will still output an action, but the simulator environment does not change from the simulation visualization interface. What is the function of the output action at this time?

**Comment by IrisLi17** [comment]
We model the bridge design and construction problem as a markov decision process with a fixed horizon of 30 just for convenience, therefore the episode will not terminate if a bridge is completed before it reaches 30 steps.

**Comment by CodingNovice7** [comment]
So when the bridge is built, but the action output does not reach a fixed horizon, is it meaningless? Will the simulator not execute? Is that so? What does the ID code - 1 in the strategy mean?

**Comment by IrisLi17** [comment]
ID=-1 refers to a dummy action that does not do anything to the simulation. If you only care about successfully designing a bridge, an alternative choice is to terminate each episode as soon as it reaches success and also remove the ``ID=-1'' trick. However, if you want to see whether the agent can adjust its design (keep moving blocks to potentially get bridges of different shapes), it is beneficial to allow the agent to run more steps after success.

**Comment by CodingNovice7** [comment]
In fact, the project generated by this bridge is similar to my current research topic, so I have been looking at the open source project of this article. Now I want to try to use the offline reinforcement learning method to learn from the data set made by the model you trained. If it can be successful, it will be very helpful to my topic, but the current learning results are not good, So now I've been looking for the reason. If you also try this, I hope you can guide the following. By the way, you said, "however, if you want to see why the agent can adjust its design (keep moving blocks to potentially get bridges of different shapes), it is beneficial to allow the agent to run more steps after success.", I don't quite understand. After the successful construction of the bridge, the output action doesn't seem to change the existing simulation environment?

**Comment by IrisLi17** [comment]
If you don't want the dummy actions after building a bridge, a quick fix is to only keep the steps before the agent gets a non-zero reward for the first time when collecting your dataset. 
With a fixed horizon, it is *possible* that an agent decides to adjust the position of some blocks after success; it is also possible that an agent chooses to perform dummy actions (as you have observed).

**Comment by CodingNovice7** [comment]
Thank you very much for your reply, thank you!
